### ISSUE TITLE
Cannot remove empty Localization CSV entry (LocaleDeleteButton > System.NullReferenceException)

### ISSUE THREAD

**Issue by hsandt** [YarnSpinnerTool/YarnSpinner-Godot#55]
Just after creating a brand new .yarnproject with no yarn script at all, using the localization and other CSV buttons will trigger errors. The most problematic one is the one preventing us from removing a Localization CSV entry added by accident or just for testing.

Repro:
- Create new .yarnproject, with no yarn scripts at all
- Click Localization CSVs > Add button (locale code doesn't matter)

![image](https://github.com/YarnSpinnerTool/YarnSpinner-Godot/assets/1067772/5b19e75e-8b28-4804-8b62-695737e78e3e)

- Try to remove it with Cross (X) button. Get error:

>   /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:112 - System.NullReferenceException: Object reference not set to an instance of an object.
     at YarnSpinnerGodot.Editor.UI.LocaleDeleteButton.OnPressed() in my_project/addons/YarnSpinner-Godot/Editor/UI/LocaleDeleteButton.cs:line 34
     at YarnSpinnerGodot.Editor.UI.LocaleDeleteButton.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in my_project/Godot.SourceGenerators/Godot.SourceGenerators.ScriptMethodsGenerator/YarnSpinnerGodot.Editor.UI.LocaleDeleteButton_ScriptMethods.generated.cs:line 36
     at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** args, Int32 argCount, godot_variant_call_error* refCallError, godot_variant* ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 24

I tried to create a dummy CSV just to attach it then remove it, but the Export Strings and Metadata as CSV button failed with:

>   /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:112 - System.NullReferenceException: Object reference not set to an instance of an object.
     at YarnSpinnerGodot.Editor.YarnProjectEditorUtility.WriteBaseLanguageStringsCSV(YarnProject project, String path) in my_project/addons/YarnSpinner-Godot/Editor/YarnProjectEditorUtility.cs:line 152
     at YarnSpinnerGodot.Editor.YarnProjectInspectorPlugin.OnBaseLanguageCSVFileSelected(String savePath) in my_project/addons/YarnSpinner-Godot/Editor/YarnProjectInspectorPlugin.cs:line 536
     at YarnSpinnerGodot.Editor.YarnProjectInspectorPlugin.<OnBaseLanguageCSVClicked>b__21_0(String savePath) in my_project/addons/YarnSpinner-Godot/Editor/YarnProjectInspectorPlugin.cs:line 529
     at Godot.Callable.<From>g__Trampoline|2_0[T0](Object delegateObj, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Callable.generics.cs:line 56
     at Godot.DelegateUtils.InvokeWithVariantArgs(IntPtr delegateGCHandle, Void* trampoline, godot_variant** args, Int32 argc, godot_variant* outRet) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/DelegateUtils.cs:line 62

so I'm stuck until I start actually working on my yarn scripts.

Ideally all the errors should have a nice handling with clear error message, or the buttons should be greyed out to prevent doing irrelevant operations.

**Comment by dogboydog** [comment]
Sorry for the issue. If the empty/undesired locale code  appears in the json of your . yarnproject file you could try removing it as a workaround. I will prevent this when I can
